const DESKTOP_SCREEN_RESOLUTION = 1280;
const TABLET_SCREEN_RESOLUTION = 768;
const MOBILE_PHONE_HIGH_SCREEN_RESOLUTION = 480;
const MOBILE_PHONE_SCREEN_RESOLUTION = 320;

const NUMBER_OF_CARDS_FOR_DESKTOP = 12;
const NUMBER_OF_CARDS_FOR_TABLET = 8;
const NUMBER_OF_CARDS_FOR_MOBILE_PHONE = 5;

const MORE_CARDS_FOR_DESKTOP = 3;
const MORE_OF_CARDS_FOR_TABLET_AND_PHONE = 2;
